spring:
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cip113}
    user: ${DB_USERNAME:cardano}
    password: ${DB_PASSWORD:password}
    schemas: ${DB_SCHEMA:public}
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/migration
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cip113}
    username: ${DB_USERNAME:cardano}
    password: ${DB_PASSWORD:password}

network: mainnet

wallet:
  mnemonic: ""

blockfrost:
  url: https://cardano-mainnet.blockfrost.io/api/v0/
  key: ""

store:
  cardano:
    host: backbone.mainnet.cardanofoundation.org
    port: 3001
    protocol-magic: 764824073
    # Start from the block that minted the ref input for the contract
    sync-start-blockhash: 586ead1770fc2a59021b824bc0d65bf1d6060585384f257971204d5925f054c2
    sync-start-slot: 154984561
    keep-alive-interval: 1000

apiPrefix: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

---
spring:
  config:
    activate:
      on-profile: preprod

network: preprod

wallet:
  mnemonic: ""

blockfrost:
  url: https://cardano-preprod.blockfrost.io/api/v0/

store:
  cardano:
    host: ""
    port: 0
    protocol-magic: 1
    sync-start-blockhash: ""
    sync-start-slot: 0

---
spring:
  config:
    activate:
      on-profile: preview

network: preview

wallet:
  mnemonic: ""

programmable.token.default.txHash: "114adc8ee212b5ded1f895ab53c7741e5521feff735d05aeef2a92dcf05c9ae2"

blockfrost:
  url: https://cardano-preview.blockfrost.io/api/v0/

store:
  cardano:
    host: ""
    port: 0
    protocol-magic: 2
    sync-start-blockhash: c196c1915bf07235284131d5f84b395061477285d74aba8634a82b5c2b22ed2f
    sync-start-slot: 69599150
